name: Docker Image CI

on:
  push:
    branches: [ "3.6.x" ]
  pull_request:
    branches: [ "3.6.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local base image
        run: docker buildx bake --load --set '*.platform=linux/amd64' -f docker/docker-bake.hcl base

      - name: Build local Poetry base image
        run: docker buildx bake --load --set '*.platform=linux/amd64' -f docker/docker-bake.hcl base-poetry

      - name: Build local builder base image
        run: docker buildx bake --load --set '*.platform=linux/amd64' -f docker/docker-bake.hcl base-builder

      - name: Build Rasa Docker image
        run: docker buildx bake --load --set '*.platform=linux/amd64' -f docker/docker-bake.hcl default
